apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "imagenet"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "gs://seldon-models/tfserving/imagenet/model"
        resources:
          requests:
            cpu: 1
            memory: 5Gi                        
          limits:
            memory: 10Gi
    explainer:
      alibi:
        type: AnchorImages
        storageUri: "gs://seldon-models/tfserving/imagenet/explainer"
        config:
          batch_size: "1"
        resources:
          requests:
            cpu: 1
            memory: 5Gi            
          limits:
            memory: 10Gi

# kubectl get inferenceservice
# kubectl get ksvc imagenet-explainer-default -o yaml
