apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: knative-monitoring-gateway
  namespace: knative-monitoring
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http-knative-services
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtual-service
  namespace: knative-monitoring
spec:
  hosts:
  - "*"
  gateways:
  - knative-monitoring-gateway
  http:
  - match:
    # - method:
    #   exact: GET
    - uri:
        prefix: /grafana/
    rewrite:
      uri: /
    route:
    - destination:
        host: grafana.knative-monitoring.svc.cluster.local
        port:
          name: http-knativegrafana
          number: 30802
          protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
  namespace: knative-monitoring
spec:
  host: grafana.knative-monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtual-service
  namespace: knative-monitoring
spec:
  hosts:
  - "*"
  gateways:
  - knative-monitoring-gateway
  http:
  - match:
    - uri:
        prefix: /prometheus/
    rewrite:
      uri: /
    route:
    - destination:
        host: prometheus-system-np.knative-monitoring.svc.cluster.local
        port:
          name: http-knativeprometheus
          number: 8080
          protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: knative-monitoring
spec:
  host: prometheus-system-np.knative-monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE