apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "microorganism"
spec:
  default:
    predictor:
      microorganism:
        storageUri: "gs://brain-ds/microorganism_13/model"