
apiVersion: v1
kind: Pod
metadata:
  name: devicequery
spec:
  containers:
    - name: nvidia
      imagePullPolicy: IfNotPresent
      image: pydemia/nvidia-jn-devicequery:r32.4.2
      command: [ "./deviceQuery" ]

